# Generated by Django 3.0.2 on 2020-01-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(max_length=100)),
                ('internal_port', models.IntegerField()),
                ('external_port', models.IntegerField()),
                ('port_type', models.CharField(max_length=20)),
            ],
        ),
    ]
