name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: centos:8

    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Install dependencies
      run: sh ./install.sh
    - name: Test Django
      run: python3 ./manage.py test
